### ISSUE TITLE
Сборка в appveyor не падает при наличии заведемо непроходящего теста

### ISSUE THREAD

**Issue by dianest** [dianest/aqa2.1#2]
# Описание проблемы

#### Предусловие 
1. В IntelliJ IDEA создан проект для тестирования на базе кода из задания
2. Для проекта используется Selenide
3. Для проекта настроен Appveyor 
4. Требования к заполнению полей соблюдены
 

#### Шаги по воспроизведению

1. Написать тест на функцию happyPath cо следующими данными:
1.1 Порт "http://localhost:9999/"
1.2 Фамилия и имя"Иванов Иван Иванович"
1.3 Телефон +"79876543210"
1.4 Чекбокс click
1.5 Ожидаемое сообщение "Ваша заявка успешно отправлена!"
2. Запустить тест
3. В Idee получить упавший тест
4. Проверить собранную сборку в Appveyor

#### Ожидаемый результат
Сборка упала, бейджик у файла README.md красный

#### Фактический результат
Сборка не упала, бейджик у файла README.md зеленый
В appveyor выводится сообщение "The build job has not produced any test results."

#### Код appveyor

```
Build started
git clone -q --branch=master https://github.com/dianest/aqa2.1.git /home/appveyor/projects/aqa2-1
git checkout -qf a610eda608a89786f789f8e75ee1e8624eb43f62
Running "install" scripts
$App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-order.jar" -PassThru
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Running "build_script" scripts
./gradlew test --info "-Dselenide.headless=true"
Running "test" phase
Running "on_finish" scripts
Stop-Process -Id $App.Id
Build completed

```

#### Программное окружение

* Intellij IDEA 2010.2 (Community Edition)
Build #IC-202.6397.94, built on July 27, 2020
* VM: OpenJDK 64-Bit server VM by JetBrains s.r.o.
* Runtime version: 11.07+10-b944.20 amd 64

**Comment by andrew-pahomov** [comment]
Добрый день, сборка в CI не выполняется. Файлу gradlew не хватает прав на запуск под Linux.       
Необходимо в секцию install файла .appveyor.yml добавить строку      
`  - chmod +x gardlew`

**Comment by dianest** [comment]
Done
